SMZG/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using SMZG.Models;

namespace SMZG.Controllers
{
    public class AlbumController : SMZGControllerBase
    {
        // GET: Album
        public ActionResult Index()
        {  
            return View();
        }

        public ActionResult Detail(string albumName)
        {
            SetAlbumItemList(albumName);
            return View();
        }

        public ActionResult GridPageListJson()
        {
            try
            {
                string filepath = Server.MapPath("~/App_Data/TestAlbum.json");
                string json = GetFileJson(filepath);
                return Content(json);
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        public ActionResult SwtychinaTime()
        {
            return View();
        }

        public ActionResult SwtychinaAlbum()
        {
            return View();
        }
    }
}

SMZG/Views/Shared/_Header.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("生命之光", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("主页", "Index", "Home")</li>
                <li>@Html.ActionLink("关于我们", "About", "Home")</li>
                <li>@Html.ActionLink("联系我们", "Contact", "Home")</li>
                <li>@Html.ActionLink("山外天园", "Swtychina", "Home")</li>
            </ul>
            @*@Html.Partial("_LoginPartial")*@
        </div>
    </div>
</div>
    

SMZG/Views/Shared/_HeaderSwtychina.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("山外天园", "Index", "Album", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("首页", "Index", "Album")</li>
                <li>@Html.ActionLink("按时间", "SwtychinaTime", "Album")</li>
                <li>@Html.ActionLink("按主题", "SwtychinaAlbum", "Album")</li>
                <li>@Html.ActionLink("生命之光", "Index", "Home")</li>
            </ul>
            @*@Html.Partial("_LoginPartial")*@
        </div>
    </div>
</div>
    

SMZG/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 生命之光</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<link href="~/Content/Swtychina.css" rel="stylesheet">*@

</head>
<body>
    @Html.Partial("~/Views/Shared/_Header.cshtml")   
    <div class="container body-content">
        @RenderBody()
        <hr />
        @Html.Partial("~/Views/Shared/_footer.cshtml")
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SMZG/Views/Shared/_LayoutSwtychian.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 生命之光</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Swtychina.css" rel="stylesheet">

</head>
<body id="swtychina">
    @Html.Partial("~/Views/Shared/_HeaderSwtychina.cshtml")
    <div class="container body-content">
        @RenderBody()
        @*<hr />
            @Html.Partial("~/Views/Shared/_footer.cshtml")*@
    </div>
    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/jquerymobile")*@
    @Scripts.Render("~/bundles/bootstrap")
    @*@Scripts.Render("~/bundles/swtyjs")*@
    @RenderSection("scripts", required: false)
</body>
</html>

SMZG/Views/Shared/_footer.cshtml
<footer class="text-center">
    <p>&copy; @DateTime.Now.Year - 生命之光教会</p>
    <script type="text/javascript">
                var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");
                document.write(unescape("%3Cspan id='cnzz_stat_icon_1271925150'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s22.cnzz.com/z_stat.php%3Fid%3D1271925150%26show%3Dpic' type='text/javascript'%3E%3C/script%3E"));
    </script>
</footer>  